### ISSUE TITLE
Envio de mensagens semanais

### ISSUE THREAD

**Issue by luisscielo** [scieloorg/themes-wordpress#17]
Toda segunda-feira às 0500h o sistema deve enviar uma mensagem para equipe@scielo.org informando os compromissos da semana. Isso às vezes acontece, às vezes não.

**Comment by fabiobatalha** [comment]
Os CRONS estão devidamente configurados.

**Possíveis verificações**
1. Query feita para recuperar eventos da agenda do WP
2. Timestamp + Timezone dos registros 
3. Rotina de envio de e-mail
