### ISSUE TITLE
Envio de mensagens com os compromissos do dia

### ISSUE THREAD

**Issue by luisscielo** [scieloorg/themes-wordpress#18]
Além da mensagem semanal, o sistema deve enviar todo dia em que houver compromissos, às 0500h, uma mensagem com os compromissos do dia. Isso não está acontecendo.

**Comment by fabiobatalha** [comment]
Os CRONS estão devidamente configurados.

**Possíveis verificações**
1. Query feita para recuperar eventos da agenda do WP
2. Timestamp + Timezone dos registros
3. Rotina de envio de e-mail
